package io.github.radiqalo.picaris.designsystem

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.res.vectorResource

enum class MaterialSymbol(val resource: Int) {
    Home(R.drawable.ms_home),
    Refresh(R.drawable.ms_refresh),
    Send(R.drawable.ms_send),
    HomeFilled(R.drawable.ms_home_filled),
    Explore(R.drawable.ms_explore),
    ExploreFilled(R.drawable.ms_explore_filled),
    Feed(R.drawable.ms_dynamic_feed),
    FeedFilled(R.drawable.ms_dynamic_feed_filled),
    Person(R.drawable.ms_person),
    PersonFilled(R.drawable.ms_person_filled),
    Image(R.drawable.ms_image),
    Hd(R.drawable.ms_hd),
    Translate(R.drawable.ms_translate),
    DockToBottom(R.drawable.ms_dock_to_bottom),
    FolderOpen(R.drawable.ms_folder_open),
    Speed(R.drawable.ms_speed),
    Edit(R.drawable.ms_edit),
    Backup(R.drawable.ms_backup),
    UploadFile(R.drawable.ms_upload_file),
    ZoomIn(R.drawable.ms_zoom_in),
    Book(R.drawable.ms_menu_book),
    Lock(R.drawable.ms_lock),
    LockOpen(R.drawable.ms_lock_open),
    Inbox(R.drawable.ms_inbox),
    Calendar(R.drawable.ms_calendar_month),
    Theme(R.drawable.ms_dark_mode),
    Wallpaper(R.drawable.ms_wallpaper),
    Palette(R.drawable.ms_palette),
    Contrast(R.drawable.ms_contrast),
    Adult(R.drawable.ms_18_up_rating),
    Ai(R.drawable.ms_smart_toy),
    BlockedTag(R.drawable.ms_label_off),
    BlockedUser(R.drawable.ms_person_off),
    Network(R.drawable.ms_public),
    ClearCache(R.drawable.ms_cleaning_services),
    Search(R.drawable.ms_search),
    Favorite(R.drawable.ms_favorite),
    FavoriteFilled(R.drawable.ms_favorite_filled),
    Comment(R.drawable.ms_chat_bubble),
    ArrowBack(R.drawable.ms_arrow_back),
    Download(R.drawable.ms_download),
    MoreHoriz(R.drawable.ms_more_horiz),
    Settings(R.drawable.ms_settings),
    ChevronRight(R.drawable.ms_chevron_right),
    Close(R.drawable.ms_close),
    Leaderboard(R.drawable.ms_leaderboard),
    History(R.drawable.ms_history),
    Share(R.drawable.ms_share),
    Check(R.drawable.ms_check),
    Pause(R.drawable.ms_pause),
    PlayArrow(R.drawable.ms_play_arrow),
    Add(R.drawable.ms_add),
    Delete(R.drawable.ms_delete),
    Sort(R.drawable.ms_sort),
    ContentCopy(R.drawable.ms_content_copy),
}

@Composable
fun materialSymbol(symbol: MaterialSymbol): ImageVector =
    ImageVector.vectorResource(symbol.resource)
